export function vectorFromSql(value: any): any;
export function vectorToSql(value: any): any;
export function sparsevecFromSql(value: any): SparseVector | null;
export function sparsevecToSql(value: any): any;
export function vectorType(dimensions: number | null | undefined): string;
export function halfvecType(dimensions: number | null | undefined): string;
export function bitType(dimensions: number | null | undefined): string;
export function sparsevecType(dimensions: number | null | undefined): string;
import { SparseVector } from './sparse-vector.js';
export { vectorFromSql as halfvecFromSql, vectorToSql as halfvecToSql };
