import { SparseVector } from './sparse-vector.js';
export declare function vectorFromSql(value: string | null): number[] | null;
export declare function vectorToSql(value: number[] | null): string | null;
export { vectorFromSql as halfvecFromSql };
export { vectorToSql as halfvecToSql };
export declare function sparsevecFromSql(value: string | null): SparseVector | null;
export declare function sparsevecToSql(value: SparseVector | null): string | null;
export declare function vectorType(dimensions: number | null | undefined): string;
export declare function halfvecType(dimensions: number | null | undefined): string;
export declare function bitType(dimensions: number | null | undefined): string;
export declare function sparsevecType(dimensions: number | null | undefined): string;
