export { BitType } from './bit.js';
export { HalfvecType } from './halfvec.js';
export { SparsevecType } from './sparsevec.js';
export { VectorType } from './vector.js';
export declare function l2Distance(column: any, value: any): import("@mikro-orm/core").RawQueryFragment<string> & symbol;
export declare function maxInnerProduct(column: any, value: any): import("@mikro-orm/core").RawQueryFragment<string> & symbol;
export declare function cosineDistance(column: any, value: any): import("@mikro-orm/core").RawQueryFragment<string> & symbol;
export declare function l1Distance(column: any, value: any): import("@mikro-orm/core").RawQueryFragment<string> & symbol;
export declare function hammingDistance(column: any, value: any): import("@mikro-orm/core").RawQueryFragment<string> & symbol;
export declare function jaccardDistance(column: any, value: any): import("@mikro-orm/core").RawQueryFragment<string> & symbol;
